services:
  m43:
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    entrypoint: ["./docker/entrypoint.sh"]
    command: ["npm", "start"]
    ports:
      - target: ${PORT}
        published: ${PORT}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        USER_HOME: /home/${USER_NAME}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
