services:
  m43:
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    entrypoint: ["./docker/entrypoint.sh"]
    ports:
      - ${PORT}:${PORT}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        USER_HOME: ${USER_HOME}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
